name = "MHLibDemos"
uuid = "684acab6-7f56-4bd3-8ecb-3989322bafbb"
version = "0.3.1"
authors = ["Guenther Raidl <raidl@ac.tuwien.ac.at> et al."]

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
Graphs = "86223c79-3864-5bf0-83f7-82e725a168b6"
MHLib = "0f3a0e6e-e0e7-4894-bd64-856f0ae3b635"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[sources]
MHLib = {path = ".."}

[compat]
CSV = "0.10.15"
DataFrames = "1.8.1"
Glob = "1.3.1"
Graphs = "1.13.1"
MHLib = "0.3"
Statistics = "1.11.1"
StatsBase = "0.34"
Test = "1.11.0"
TestItemRunner = "1.1.0"
TestItems = "1"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
TestItemRunner = "f8b46487-2199-4994-9208-9a1283c18c0a"

[targets]
test = ["Test", "TestItemRunner"]
